name: telegram-glm-bot
services:
  - name: bot
    type: worker
    env: python
    build_command: pip install -r requirements.txt
    run_command: python bot.py
    env_vars:
      - key: GLM_API_KEY
        value: "{{ .GLM_API_KEY }}"
      - key: TELEGRAM_BOT_TOKEN
        value: "{{ .TELEGRAM_BOT_TOKEN }}"
